# Generated by Django 5.2.1 on 2025-06-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_newsculture_slug_newsimage_slug_newssport_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsimage',
            name='description',
            field=models.TextField(blank=True, max_length=1400, null=True, verbose_name='Описание'),
        ),
    ]
