# Generated by Django 5.2.1 on 2025-06-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_newsimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsculture',
            name='description',
            field=models.TextField(blank=True, max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='newssport',
            name='description',
            field=models.TextField(blank=True, max_length=1400, null=True, verbose_name='Описание'),
        ),
    ]
